###Sign-up
POST http://localhost:3001/users
Content-Type: application/json

{
    "firstName": "Ngan",
    "lastName": "Le",
    "email": "lengan@gmail.com",
    "password": "123123",
    "posts": []
}

###Check Valid Token
PUT http://localhost:3001/auth/valid
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE1MTg0ODk3LCJleHAiOjE3MTUxODg0OTd9.3dADejkibq2-Fb23UrhqT4ZUUpuO2FmYhSfs5iPZ60w

###Update-User-Using-Token
PUT http://localhost:3001/auth/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE0Mjg3MDExLCJleHAiOjE3MTQzNzM0MTF9.Bxga5JxlrYODVvA1nl2zOcFnXK5WXZK6WfiPxLQKQMg

{
    "firstName": "Tannnn",
    "lastName": "Trann",
    "email": "",
    "password": ""
}

###Find-Owned-User-Using-Token
GET http://localhost:3001/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE0Mjg3MDExLCJleHAiOjE3MTQzNzM0MTF9.Bxga5JxlrYODVvA1nl2zOcFnXK5WXZK6WfiPxLQKQMg

###Login¸
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "tantran2802@gmail.com",
    "password": "123123"
}

###Search-Using-Keyword
GET http://localhost:3001/posts/search?keyword=ewkllwekckle


###Posting-Using-Token
POST http://localhost:3001/posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE1MTg0ODk3LCJleHAiOjE3MTUxODg0OTd9.3dADejkibq2-Fb23UrhqT4ZUUpuO2FmYhSfs5iPZ60w

{
    "content": "Hello name\nPlease",
    "images": ["https://i.pinimg.com/736x/63/8f/e3/638fe33412a4d1de766b126497f4ef42.jpg", "https://i.pinimg.com/564x/e8/3b/4f/e83b4f5a00d83a975707eab32af8d5ea.jpg"]
}

###Find-All-Posts-Publicly-Pagination
GET http://localhost:3001/posts?limit=26


###Find-Posts-By-Id-Optional
GET http://localhost:3001/posts/user?option=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE2MTkzNDExLCJleHAiOjE3MTYxOTcwMTF9.sYhiRx5a4_4qDkWyoCLisXBTvEPcotnn_plrRCgU6kk


###Create-Image-From-Post
POST http://localhost:3001/posts/6/images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE0NzMyMzE3LCJleHAiOjE3MTQ3MzU5MTd9.RU7pLHD5o5VECEPJizukja9aN6UkxIMyoWTP6Denl9A

{
    "urls": ["https://i.pinimg.com/564x/35/4d/93/354d933b42faaa6fcb14832825e88a93.jpg", "https://i.pinimg.com/564x/0d/b4/6d/0db46d0fd1163fafd2fd3598e1e9727d.jpg"]
}

###
GET http://localhost:3001/posts/all

###Update Post only Content -- Because findOne(postId, { relations: ['images'] }) this method only receive 1 argument (oldversion) and Cannot query across one-to-many for property images The error message "Cannot query across one-to-many for property images" typically occurs when you are trying to perform a query or an update that involves navigating through a OneToMany relationship directly, which TypeORM does not support in some contexts.
PUT http://localhost:3001/posts/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE1ODI5ODA4LCJleHAiOjE3MTU4MzM0MDh9.yuSTjVpgwUmG3e9QV5mKd6MwwkY7KdX0ctj_pFHoO70

{
    "content": "Putin arrives in Beijing for China state visit as Ukraine war intensifies\nRussian news agency Tass reports that Russia's president has brought a large delegation consisting of five deputy prime ministers, heads of economic, diplomatic and security agencies, as well as the heads of some Russian state energy companies."
}

###Update Images
PUT http://localhost:3001/posts/14/images/15
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE1ODM5ODc3LCJleHAiOjE3MTU4NDM0Nzd9.r9yEtM1cV8DuU2OQfKJppScLnb3-Q0sRlFBqlhnxVsY

{
    "url": "https://i.pinimg.com/736x/14/9a/a8/149aa8ca7ded76a2b5f6c55af9dd5f7c.jpg"
}

###Find Image via PostId and ImageId
GET http://localhost:3001/posts/1/images/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRhbnRyYW4yODAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MiwiaWF0IjoxNzE2MTkzNDExLCJleHAiOjE3MTYxOTcwMTF9.sYhiRx5a4_4qDkWyoCLisXBTvEPcotnn_plrRCgU6kk