service: nestjs-app

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: dist/lambda.handler
    events:
      - http:
          path: /
          method: get

package:
  individually: true
  exclude:
    - node_modules/**
    - test/**
    - coverage/**

plugins:
  - serverless-nestjs
